CC=gcc
CFLAGS=-std=c11 -Wpedantic -Wall -Wextra
LDLIBS=-lm
RM=rm -f
OBJ=main.o convertion.o
EXE=main
$(EXE):$(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(EXE) $(LDLIBS)
main.o:main.c convertion.h
	$(CC) $(CFLAGS) -c main.c
conversion.o:convertion.c convertion.h
	$(CC) $(CFLAGS) -c convertion.c
clean:
	$(RM) $(OBJ) $(EXE)