CC=gcc
CFLAGS=-std=c11 -Wpedantic -Wall -Wextra
LDLIBS=-lm
RM=rm -f
OBJ=main.o convertion.o strManipulation.o
EXE=main
$(EXE):$(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $(EXE) $(LDLIBS)
main.o:main.c convertion.h strManipulation.h
	$(CC) $(CFLAGS) -c main.c
conversion.o:convertion.c convertion.h strManipulation.h
	$(CC) $(CFLAGS) -c convertion.c
strManipulation.o:strManipulation.c strManipulation.h
	$(CC) $(CFLAGS) -c strManipulation.c
clean:
	$(RM) $(OBJ) $(EXE)